### ISSUE TITLE
invalid exe generated when injecting in contructor

### ISSUE THREAD

**Issue by scott-adamson1975** [keeper013/CrossCutterN#7]
the injected exe works, but peverity claims that there is an error in the regenerated IL

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [E:\Desarrollo\Codigo\DOT NET\Aplicaciones Auxiliares\InjectedLogging\CrossCutterN\CrossCutterN.Sample.Target\bin\Release\CrossCutterN.Sample.Target.exe : CrossCutterN.Sample.Target.Target::.ctor][offset 0x0000002E][found <uninitialized> ref ('this' ptr) 'CrossCutterN.Sample.Target.Target'][expected ref 'System.Object'] Unexpected type on the stack.
1 Error(s) Verifying E:\Desarrollo\Codigo\DOT NET\Aplicaciones Auxiliares\InjectedLogging\CrossCutterN\CrossCutterN.Sample.Target\bin\Release\CrossCutterN.Sample.Target.exe

[CrossCutterN.Trace.Advice.Attribute.Log.Informacion]
public Target()
{
    Console.Out.WriteLine("hey ho, lets go ");
}

namespace CrossCutterN.Trace.Advice.Attribute.Log
{
    using CrossCutterN.Base.Concern;
    using System;
    [AttributeUsage(AttributeTargets.All)]
    public abstract class LogAttribute : ConcernMethodAttribute
    { public abstract int Level { get; } }
}

namespace CrossCutterN.Trace.Advice.Attribute.Log
{
    [AttributeUsage(AttributeTargets.All)]
    public sealed class InformacionAttribute : LogAttribute
    {
        public override int Level => 150;
    }
}

constructor as seen in dotpeek after injection

    public Target()
    {
      bool flag = SwitchBackStage.Glancer.IsOn(CrossCutterN.Sample.Target.Target._aCVolDhi_);
      IExecution execution;
      if (flag)
        execution = MetadataFactory.InitializeExecution("CrossCutterN.Sample.Target, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null", "CrossCutterN.Sample.Target", "CrossCutterN.Sample.Target.Target", nameof (Target), this.GetHashCode(), "System.Void CrossCutterN.Sample.Target.Target::.ctor()", ".ctor", "System.Void").Build();
      IReturnBuilder returnBuilder1;
      if (flag)
        returnBuilder1 = MetadataFactory.InitializeReturn("System.Void");
      try
      {
        if (flag)
          TraceByAttribute.OnEntry(execution);
        // ISSUE: explicit constructor call
        base.\u002Ector();
        Console.Out.WriteLine("hey ho, lets go ");
      }
      finally
      {
        IReturn rReturn;
        if (flag)
        {
          IReturnBuilder returnBuilder2 = returnBuilder1;
          returnBuilder2.HasReturn = false;
          rReturn = returnBuilder2.Build();
        }
        if (flag)
          TraceByAttribute.OnExit(execution, rReturn);
      }
    }

il code after injection

.method public hidebysig specialname rtspecialname instance void 
    .ctor() cil managed 
  {
    .custom instance void [CrossCutterN.Trace.Advice]CrossCutterN.Trace.Advice.Attribute.Log.InformacionAttribute::.ctor() 
      = (01 00 00 00 )
    .maxstack 8
    .locals init (
      [0] class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IExecutionBuilder V_0,
      [1] class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IExecution execution,
      [2] class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IReturnBuilder returnBuilder1,
      [3] bool flag,
      [4] class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IReturn rReturn
    )

    // [24 7 - 24 93]
    IL_0000: call         class [CrossCutterN.Base]CrossCutterN.Base.Switch.IAspectSwitchGlancer [CrossCutterN.Base]CrossCutterN.Base.Switch.SwitchBackStage::get_Glancer()
    IL_0005: ldsfld       int32 CrossCutterN.Sample.Target.Target::_aCVolDhi_
    IL_000a: callvirt     instance bool [CrossCutterN.Base]CrossCutterN.Base.Switch.IAspectSwitchGlancer::IsOn(int32)
    IL_000f: stloc        flag

    // [26 7 - 26 16]
    IL_0013: ldloc        flag
    IL_0017: brfalse.s    IL_0050

    // [27 9 - 27 335]
    IL_0019: ldstr        "CrossCutterN.Sample.Target, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null"
    IL_001e: ldstr        "CrossCutterN.Sample.Target"
    IL_0023: ldstr        "CrossCutterN.Sample.Target.Target"
    IL_0028: ldstr        "Target"
    IL_002d: ldarg.0      // this
    IL_002e: callvirt     instance int32 [mscorlib]System.Object::GetHashCode()
    IL_0033: ldstr        "System.Void CrossCutterN.Sample.Target.Target::.ctor()"
    IL_0038: ldstr        ".ctor"
    IL_003d: ldstr        "System.Void"
    IL_0042: call         class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IExecutionBuilder [CrossCutterN.Base]CrossCutterN.Base.Metadata.MetadataFactory::InitializeExecution(string, string, string, string, int32, string, string, string)
    IL_0047: callvirt     instance !0/*class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IExecution*/ class [CrossCutterN.Base]CrossCutterN.Base.Common.IBuilder`1<class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IExecution>::Build()
    IL_004c: stloc        execution

    // [29 7 - 29 16]
    IL_0050: ldloc        flag
    IL_0054: brfalse.s    IL_0064

    // [30 9 - 30 73]
    IL_0056: ldstr        "System.Void"
    IL_005b: call         class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IReturnBuilder [CrossCutterN.Base]CrossCutterN.Base.Metadata.MetadataFactory::InitializeReturn(string)
    IL_0060: stloc        returnBuilder1
    .try
    {

      // [33 9 - 33 18]
      IL_0064: ldloc        flag
      IL_0068: brfalse.s    IL_0073

      // [34 11 - 34 46]
      IL_006a: ldloc        execution
      IL_006e: call         void [CrossCutterN.Trace.Advice]CrossCutterN.Trace.Advice.TraceByAttribute::OnEntry(class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IExecution)

      // [36 9 - 36 26]
      IL_0073: ldarg.0      // this
      IL_0074: call         instance void [mscorlib]System.Object::.ctor()

      // [37 9 - 37 50]
      IL_0079: call         class [mscorlib]System.IO.TextWriter [mscorlib]System.Console::get_Out()
      IL_007e: ldstr        "hey ho, lets go "
      IL_0083: callvirt     instance void [mscorlib]System.IO.TextWriter::WriteLine(string)

      IL_0088: leave        IL_00bb
    } // end of .try
    finally
    {

      // [42 9 - 42 18]
      IL_008d: ldloc        flag
      IL_0091: brfalse.s    IL_00a7

      // [44 11 - 44 57]
      IL_0093: ldloc        returnBuilder1
      IL_0097: dup          

      // [45 11 - 45 43]
      IL_0098: ldc.i4.0     
      IL_0099: callvirt     instance void [CrossCutterN.Base]CrossCutterN.Base.Metadata.IReturnBuilder::set_HasReturn(bool)

      // [46 11 - 46 43]
      IL_009e: callvirt     instance !0/*class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IReturn*/ class [CrossCutterN.Base]CrossCutterN.Base.Common.IBuilder`1<class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IReturn>::Build()
      IL_00a3: stloc        rReturn

      // [48 9 - 48 18]
      IL_00a7: ldloc        flag
      IL_00ab: brfalse.s    IL_00ba

      // [49 11 - 49 54]
      IL_00ad: ldloc        execution
      IL_00b1: ldloc        rReturn
      IL_00b5: call         void [CrossCutterN.Trace.Advice]CrossCutterN.Trace.Advice.TraceByAttribute::OnExit(class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IExecution, class [CrossCutterN.Base]CrossCutterN.Base.Metadata.IReturn)

      IL_00ba: endfinally   
    } // end of finally
    IL_00bb: ret          

  } // end of method Target::.ctor

**Comment by scott-adamson1975** [comment]
The weaving log 

Assembly Name: CrossCutterN.Sample.Target, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
Weaved: 1 modules, 1 classes, 3 methods, 0 properties, 3 switches.

	Module: CrossCutterN.Sample.Target.exe
	Added 0 assembly references:

	Weaved 1 classes, 3 methods, 0 properties, 3 switches.

		Class: CrossCutterN.Sample.Target.Target
		Weaved 3 methods, 0 properties, 3 switches

			Method: System.Void CrossCutterN.Sample.Target.Target::.ctor()
			2 advices weaved
				Entry 0 CrossCutterN.Trace.Advice.TraceByAttribute.OnEntry(CrossCutterN.Base.Metadata.IExecution) logInformacionByAttribute
				Exit 0 CrossCutterN.Trace.Advice.TraceByAttribute.OnExit(CrossCutterN.Base.Metadata.IExecution,CrossCutterN.Base.Metadata.IReturn) logInformacionByAttribute

			Method: System.Int32 CrossCutterN.Sample.Target.Target::Add(System.Int32,System.Int32)
			2 advices weaved
				Entry 0 CrossCutterN.Trace.Advice.TraceByAttribute.OnEntry(CrossCutterN.Base.Metadata.IExecution) logInformacionByAttribute
				Exit 0 CrossCutterN.Trace.Advice.TraceByAttribute.OnExit(CrossCutterN.Base.Metadata.IExecution,CrossCutterN.Base.Metadata.IReturn) logInformacionByAttribute

			Method: System.Void CrossCutterN.Sample.Target.Target::Add()
			2 advices weaved
				Entry 0 CrossCutterN.Trace.Advice.TraceByAttribute.OnEntry(CrossCutterN.Base.Metadata.IExecution) logInformacionByAttribute
				Exit 0 CrossCutterN.Trace.Advice.TraceByAttribute.OnExit(CrossCutterN.Base.Metadata.IExecution,CrossCutterN.Base.Metadata.IReturn) logInformacionByAttribute

			Switches:
				_MBza4aT8_: CrossCutterN.Sample.Target.Target  .ctor() logInformacionByAttribute False
				_zQBePzPq_: CrossCutterN.Sample.Target.Target  Add(System.Int32,System.Int32) logInformacionByAttribute False
				_I586m62h_: CrossCutterN.Sample.Target.Target  Add() logInformacionByAttribute False

**Comment by keeper013** [comment]
This issue has been fixed, the code has been updated, and the working binaries is pending for verification before becoming available to public.
Cause of issue: instance constructors compiled to IL will call parent constructors first, this parent constructor calling code should always be the first instructions to be executed and never affected by il weaving code. The original implementation didn't consider that.
@scott-adamson1975 : Thanks a lot for your help to report this bug.
