### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null. Parameter name: nameSpace

### ISSUE THREAD

**Issue by jiaxiang8756** [keeper013/CrossCutterN#8]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/24407397/116351941-066e1280-a827-11eb-957a-d25e7b6d0f99.png">

and Reflector  msg
<img width="1687" alt="image" src="https://user-images.githubusercontent.com/24407397/116352028-28679500-a827-11eb-95f6-9c7b99c3c3de.png">
config:
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/24407397/116352093-3c12fb80-a827-11eb-9d2c-8e69330f8c54.png">
<img width="820" alt="image" src="https://user-images.githubusercontent.com/24407397/116352114-43d2a000-a827-11eb-927f-d2647f88209a.png">

**Comment by keeper013** [comment]
could I confirm with you that you injected a class that is not in any namespace?

**Comment by jiaxiang8756** [comment]
impossible 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/24407397/116489960-c8c1c600-a8c8-11eb-929e-c48d02c8c60a.png">


<img width="1186" alt="image" src="https://user-images.githubusercontent.com/24407397/116490040-06beea00-a8c9-11eb-9311-1905184e9d8d.png">

both have namespace....

**Comment by keeper013** [comment]
Is it possible for you to send the source code to keeper013@gmail.com for me to reproduce this issue?

**Comment by jiaxiang8756** [comment]
OK

**Comment by keeper013** [comment]
Hi Jiaxiang, I can't open the URL in your email, could you a zip file of your code to keeper013@gmail.com?

**Comment by jiaxiang8756** [comment]
sorry，Gmail doesn't allow some attachments to be uploaded because they don't think they're secure

**Comment by jiaxiang8756** [comment]
https://www.dropbox.com/s/0yfaxgyoc1vw0u2/project.zip?dl=0

**Comment by keeper013** [comment]
Hi Jiaxiang, there are 2 missing files in the uploaded web app project (Please refer to the attached screenshot). Though I managed to build the dll by excluding them from the project, it seems I can't run the web app without them. Could you provide these files so I can try to reproduce this problem?

Thanks.

![missingFiles](https://user-images.githubusercontent.com/28725606/116799347-2ce3c480-ab2b-11eb-9c2d-3756db277571.png)

if possible, could you also provide the call stack when the exception happens? According to the reflector message the nameSpace parameter has been passed the value "WebApplication1", so I doubt if the exception comes from GetUserById method.

**Comment by keeper013** [comment]
Got no following up from the issue submitter
